### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by j-norwood-young** [TheFox/cmus-control#1]
Hi there

I get the following when I try and build:

```
> make
which -a cmake
make: *** [setup] Error 1
```

Not sure if I'm missing some dependencies?

Thanks!

**Comment by TheFox** [comment]
Hey,

yes, you need to install `cmake`.

You can run `which -a cmake` manually and when there is no output from the `which` command `cmake` is missing.

Br

**Comment by j-norwood-young** [comment]
Thanks! 

```
brew install cmake
make
make install
```

**Comment by TheFox** [comment]
Thank you. I added this step to the README documentation.
