### ISSUE TITLE
Running as launchctl daemon doesn't work

### ISSUE THREAD

**Issue by leana8959** [TheFox/cmus-control#11]
Hello,

Running `cmuscontrold` works perfectly yet `brew services start thefox/brewery/cmus-control` (with and without sudo because brew prompted me to use sudo) doesn't work. I tried to install manually too, but it still doesn't work. What could've gone wrong?

Really appreciate your project,
Léana.

**Comment by apexatoll** [comment]
If you're on a silicon Mac you will need to update the services plist file to add `/opt/homebrew/bin` to the path so that homebrew can find `cmuscontrold`

Go to
`/opt/homebrew/Cellar/cmus-control` and find the homebrew plist file. Update the Path tags to:

```
<key>PATH</key>
<string>/opt/homebrew/bin:usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin</string>
```

**Comment by leana8959** [comment]
It works like a charm now, thanks !!

**Comment by TheFox** [comment]
@leana8959 Thank you for pointing out this issue.

@apexatoll Thank you for sharing the fix. I will add it to the .plist file.

Edit: @apexatoll You missing one `/` in `/opt/homebrew/bin:usr/local/bin`. Right before `usr/`.
