### ISSUE TITLE
On Mojave, daemon not auto-launching

### ISSUE THREAD

**Issue by sqeeezy** [TheFox/cmus-control#13]
Macos 10.14.6 - I did the manual install, 
then disabled noTunes in my login items in System Preferences/Users & Groups/Login Items, 
did the launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist spell and checked iTunes wouldn't launch in response to the media keys. 
Did the "load" version of the above spell to check iTunes would launch and then another "unload".
I launched cmus and got no response from the media keys. 
Looking at top and Activity Monitor showed cmuscontrold but it wasn't running until I typed  cmuscontrold in Terminal. 
All ok after that. 
Just checked to confirm that /usr/local/bin is in my PATH.
Checked that   at.fox21.cmuscontrold.plist exists in ~/Library/LaunchAgents, 
but it didn't start the cmuscontrold daemon for me after a restart.

**Comment by TheFox** [comment]
What does `brew services` say?

> Looking at top and Activity Monitor showed cmuscontrold but it wasn't running until I typed cmuscontrold in Terminal.

What does it mean, it showed in `top` and Activity Monitor but it wasn't running? If you see it in `top` and Activity Monitor it is running, right?

**Comment by sqeeezy** [comment]
Homebrew's not supported on Mojave. I use MacPorts but I followed the instructions for manual installation. 
" If you see it in top and Activity Monitor it is running, right?" Yes, it's running, but it has no effect on cmus unless I actively invoke it by typing "cmuscontrold" in a dedicated Terminal window, then start cmus in another window. 
This results in two instances of cmuscontrold in Activity Monitor, until I kill the daemon by shutting down its window. 

After that I followed the fish function instructions on this page https://medium.com/@leana.jiang.2002/ditching-apples-music-app-in-favour-of-cmus-f73e785468b9   but it's not much better than starting the daemon manually. 

This copy from Terminal shows me that the cmuscontrold.plist is already loaded
/Users/nik:launchctl load -w Library/LaunchAgents/at.fox21.cmuscontrold.plist
/Users/nik/Library/LaunchAgents/at.fox21.cmuscontrold.plist: service already loaded

**Comment by sqeeezy** [comment]
Probably a dumb noob question......Does it matter that cmus and cmus-remote are in /opt/local/bin, where MacPorts installed them, and cmuscontrold is in /usr/local/bin? Both in PATH.

**Comment by sqeeezy** [comment]
Ok, woke up this morning and the penny dropped. Q.V. above post. Edited ~/Library/LaunchAgents/at.fox21.cmuscontrold.plist to change /opt/homebrew/bin to /opt/local/bin, rebooted and all is ok. Suggest amending installation instructions to cover this situation where homebrew is not installed. Problem closed. Thanks for your work on producing cmuscontrold, I do find it convenient to be able to use standard keys, easily locateable in the dark.
