### ISSUE TITLE
NX_KEYTYPE_REWIND and NX_KEYTYPE_FAST does not work 

### ISSUE THREAD

**Issue by romanzolotarev** [TheFox/cmus-control#2]
Rewind and Fast-forward keys does not work. When pressed nothing happens.

From command line it works as expected though. Tested on:

```
$ cmus-remote -n
$ cmus-remote -r
```
### Notes
- Play/pause works fine.
- OS X version: 10.11.4 (15E65)
- Installed as `TARGET=10.11 make install`.

**Comment by TheFox** [comment]
- Is the `cmuscontrold` process running?
- Which OS do you use?

**Comment by romanzolotarev** [comment]
Christian, thank you for such quick response. 

Yes, `cmuscontrold` is running.

```
$ ps -ax | grep cmuscontrold
1936 ??         0:00.06 /usr/local/bin/cmuscontrold
```

**Comment by TheFox** [comment]
Restart it and check again if it's already not working. Which OS to you use?

**Comment by romanzolotarev** [comment]
Restart did help! Weird, why play/pause has been working since install, while Rewind/FF stared working after restart only. 

Thank you!

**Comment by TheFox** [comment]
Did you read my blog post about Cmus and Media Keys? http://blog.fox21.at/2015/11/20/control-cmus-with-media-keys.html

Or at least the [Install Instructions](https://github.com/TheFox/cmus-control#install), to ensure that this isn't an issue in combination with iTunes.

**Comment by romanzolotarev** [comment]
Yes, I had read both before I run `make install` and followed the instruction.

But I had Vox player installed long time ago, maybe that was interfering somehow. Removing it now, when everything is working, just in case.

**Comment by TheFox** [comment]
Ok, cool. Thank you for using Cmus Control! :)

**Comment by romanzolotarev** [comment]
Thank you for amazing support. :)
