### ISSUE TITLE
cmus-control doesn't compile under osx 10.10.5

### ISSUE THREAD

**Issue by thepigeonoftime** [TheFox/cmus-control#6]
Hi,
when trying to compile with `$ sudo TARGET=10.10 make install`  I get  
`sudo -v`
`sudo cp tmp/at.fox21.cmuscontrold.plist /Library/LaunchAgents`
`install -c build/release/target_10.10/bin/cmuscontrold /usr/local/bin`
`install: build/release/target_10.10/bin/cmuscontrold: No such file or directory`
`make: *** [install] Error 71`                                                                                                    

using the latest homebrew cmake.
Any ideas?

**Comment by TheFox** [comment]
Did you first run `$ TARGET=10.10 make` like it's described in README?

Or did you just run

```
$ brew install cmake
$ sudo TARGET=10.10 make install
```

?

**Comment by thepigeonoftime** [comment]
I did run `$ TARGET=10.10 make`, although I had tried building without target flags first so I cloned it fresh and now got errors about an empty CMAKE_OSX_SYSROOT (see screenshot) which I 'fixed' by setting it to "10.10". Then the same error as above appears. 

![screen-shot-2016-10-21](https://cloud.githubusercontent.com/assets/4933693/19599200/da68b272-979f-11e6-9467-7942285b9ae5.jpg)
[CMakeOutput.txt](https://github.com/TheFox/cmus-control/files/544337/CMakeOutput.txt)

**Comment by TheFox** [comment]
It seems that you don't have the Mac OS X SDK 10.10 installed. Look into `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs` by executing

```
$ ls -la /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
```

The variable `CMAKE_OSX_SYSROOT` needs to be set to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk` if you want to build it for a 10.10 target.

`CMAKE_OSX_SYSROOT` needs to be equal or greater than the target (`CMAKE_OSX_DEPLOYMENT_TARGET`). For example: you can build it for a 10.9 target using an SDK version 10.9, 10.10, 10.11, etc. If you don't have the 10.10 SDK installed you either need to install SDK 10.10 or build to a lower target than 10.10. For example against 10.9. But it needs to be >10.6.

**Comment by thepigeonoftime** [comment]
My bad, I thought xcodes command line tools would suffice. I'll try again with a full install. Thanks.

**Comment by TheFox** [comment]
You are welcome. Tell me when it works.

**Comment by thepigeonoftime** [comment]
Builds and works fine with Xcode installed and `CMAKE_OSX_SYSROOT` set to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk`
Thanks again!

**Comment by TheFox** [comment]
Nice!
